"""
prompts.py — Prompt assembly for the GPT image generation / editing API calls.

Each frame in the 7-step storyboard is generated by a different prompt:
  - Frame 1  → build_first_frame_prompt()  — generate from scratch
  - Frames 2–7 → build_edit_prompt()       — inpainting edit of the previous frame

Both public functions assemble their prompts from five modular blocks:
  _build_story_context()   — teaching context: subject, grade, misconceptions,
                              current step goal and delta
  _build_canvas_zones()    — describes the 1536×1024 canvas and reserved zones
  _build_notation()        — serialises all style rules from the scene_bible
  _plan_spec_block()       — FORBIDDEN / KEEP / ADD ONE instructions for this step
  _build_render_contract() — strict consistency rules to reduce model improvisation

_UNIVERSAL_RULES is appended to every prompt as an inviolable guardrail list.

Nothing in this file calls OpenAI; it only builds and returns strings.
"""

from __future__ import annotations


def _stringify_mapping(title: str, value: object) -> list[str]:
    """Serialize a dict, list, or str into indented bullet lines for a prompt block."""
    lines: list[str] = []
    if isinstance(value, dict) and value:
        lines.append(f"  {title}:")
        for k, v in value.items():
            lines.append(f"    {k}: {v}")
    elif isinstance(value, list) and value:
        lines.append(f"  {title}:")
        for item in value:
            lines.append(f"    - {item}")
    elif isinstance(value, str) and value.strip():
        lines.append(f"  {title}: {value}")
    return lines


def _build_canvas_zones(plan: dict) -> str:
    """Return a formatted string describing the canvas size and zone layout.

    Reads layout from plan['scene_bible']['layout']. Handles missing or
    string-typed layout values gracefully by substituting defaults.
    The RESERVED ZONE (y=800-1024) must always be kept clear for the Python
    caption band added by add_bottom_caption() in utils.py.
    """
    scene_bible = plan.get("scene_bible", {})
    if not isinstance(scene_bible, dict):
        scene_bible = {}

    layout = scene_bible.get("layout", {})
    if isinstance(layout, str):
        layout = {
            "canvas": "1536x1024 px",
            "zones": {
                "DIAGRAM ZONE y=0-800": layout,
                "RESERVED ZONE y=800-1024": "leave empty for Python caption.",
            },
        }
    elif not isinstance(layout, dict):
        layout = {}

    canvas = layout.get("canvas", "1536x1024 px")
    if not isinstance(canvas, str):
        canvas = "1536x1024 px"

    zones = layout.get("zones", {})
    if isinstance(zones, str):
        zones = {
            "DIAGRAM ZONE y=0-800": zones,
            "RESERVED ZONE y=800-1024": "leave empty for Python caption.",
        }
    elif not isinstance(zones, dict):
        zones = {}

    if zones:
        zone_lines = "\n".join(f"  {name}: {purpose}" for name, purpose in zones.items())
    else:
        zone_lines = (
            "  DIAGRAM ZONE  y=0-800: all visual elements.\n"
            "  RESERVED ZONE y=800-1024: leave empty for Python caption."
        )

    return f"Canvas: {canvas}. White background.\nZone layout:\n{zone_lines}"


def _build_notation(plan: dict) -> str:
    """Serialize all style rules from plan['scene_bible'] into a STYLE RULES block.

    Reads: style, background, typography, educational_contract, colour_contract,
    color_palette, safe_zones, object_design, global_rules,
    allowed_visual_elements, forbidden_elements.
    String-typed sub-fields are normalised to single-key dicts before serialisation.
    """
    bible = plan.get("scene_bible", {})
    if not isinstance(bible, dict):
        bible = {}
    lines = ["STYLE RULES:"]

    style = bible.get("style", "flat-vector 2D educational illustration")
    lines.append(f"  style: {style}")

    background = bible.get("background")
    if isinstance(background, str) and background.strip():
        lines.append(f"  background: {background}")

    typography = bible.get("typography", {})
    if isinstance(typography, str):
        typography = {"summary": typography}
    elif not isinstance(typography, dict):
        typography = {}
    if typography:
        for k, v in typography.items():
            lines.append(f"  {k}: {v}")

    educational_contract = bible.get("educational_contract", {})
    if isinstance(educational_contract, str):
        educational_contract = {"summary": educational_contract}
    elif not isinstance(educational_contract, dict):
        educational_contract = {}
    if educational_contract:
        lines.append("  educational contract:")
        for k, v in educational_contract.items():
            if isinstance(v, list):
                lines.append(f"    {k}: " + " | ".join(str(item) for item in v))
            else:
                lines.append(f"    {k}: {v}")

    colors = bible.get("colour_contract", {})
    if isinstance(colors, str):
        colors = {"summary": colors}
    elif not isinstance(colors, dict):
        colors = {}
    if colors:
        lines.append("  color contract:")
        for k, v in colors.items():
            lines.append(f"    {k}: {v}")

    color_palette = bible.get("color_palette")
    if isinstance(color_palette, dict) and color_palette:
        lines.append("  additional color palette:")
        for k, v in color_palette.items():
            lines.append(f"    {k}: {v}")

    safe_zones = bible.get("safe_zones")
    lines.extend(_stringify_mapping("safe_zones", safe_zones))

    object_design = bible.get("object_design")
    lines.extend(_stringify_mapping("object_design", object_design))

    global_rules = bible.get("global_rules")
    lines.extend(_stringify_mapping("global_rules", global_rules))

    allowed = bible.get("allowed_visual_elements", [])
    if isinstance(allowed, str):
        allowed = [allowed]
    elif not isinstance(allowed, list):
        allowed = []
    if allowed:
        lines.append("  allowed elements: " + "; ".join(str(x) for x in allowed))

    forbidden = bible.get("forbidden_elements", [])
    if isinstance(forbidden, str):
        forbidden = [forbidden]
    elif not isinstance(forbidden, list):
        forbidden = []
    if forbidden:
        lines.append("  never draw: " + "; ".join(forbidden))

    return "\n".join(lines)


def _build_story_context(plan: dict, step_idx: int) -> str:
    """Return a TEACHING CONTEXT block for the prompt of step step_idx.

    Extracts the question, answer, visual_family, grade/subject, and the GPT-
    generated pedagogical brief (grade_guidance, instructional_approach,
    misconceptions_to_avoid) from plan['scene_bible']['educational_contract'].
    Also injects the current step's goal and delta so the model knows exactly
    what teaching moment this frame represents.
    """
    steps = plan.get("steps", [])
    step = steps[step_idx - 1] if 0 < step_idx <= len(steps) else {}
    question = str(plan.get("question_text", ""))
    answer = str(plan.get("canonical_answer", ""))
    visual_family = str(plan.get("visual_family", "educational_diagram"))
    grade = plan.get("grade")
    subject = str(plan.get("subject", "General"))
    goal = str(step.get("goal", f"Step {step_idx}"))
    delta = str(step.get("delta", ""))
    audience = f"Grade {grade} students" if isinstance(grade, int) else "school-age learners"

    # Pull GPT-generated pedagogical brief from scene_bible.educational_contract
    bible = plan.get("scene_bible", {})
    if not isinstance(bible, dict):
        bible = {}
    ed_contract = bible.get("educational_contract", {})
    if not isinstance(ed_contract, dict):
        ed_contract = {}
    grade_guidance_text = (
        ed_contract.get("grade_guidance")
        or "Use age-appropriate educational clarity and low visual clutter."
    )
    instructional_approach = ed_contract.get("instructional_approach", "")
    misconceptions = ed_contract.get("misconceptions_to_avoid", [])
    if not isinstance(misconceptions, list):
        misconceptions = []

    lines = [
        "TEACHING CONTEXT:",
        f"  visual_family: {visual_family}",
        f"  subject: {subject}",
        f"  audience: {audience}",
        f"  grade_guidance: {grade_guidance_text}",
    ]
    if instructional_approach:
        lines.append(f"  instructional_approach: {instructional_approach}")
    if misconceptions:
        lines.append(f"  misconceptions_to_avoid: {'; '.join(str(m) for m in misconceptions)}")
    lines += [
        f"  question: {question}",
        f"  correct_explanation: {answer}",
        f"  current_step_goal: {goal}",
        f"  current_step_delta: {delta}",
        "  Requirement: Every visual element must directly support this explanation.",
        "  Do NOT introduce unrelated objects, decorative scenery, or off-topic metaphors.",
        "  The frame should feel like a teacher-designed instructional diagram, not a generic poster.",
        "  Keep the visual load low enough that a student can understand the main idea at a glance.",
    ]
    return "\n".join(lines)


def _plan_spec_block(plan: dict, step_idx: int) -> str:
    """Return the FORBIDDEN / KEEP / ADD ONE instruction block for step step_idx.

    Tells the image model exactly:
      - FORBIDDEN: elements that must not be drawn or changed
      - KEEP:      elements from all previous steps to preserve unchanged
      - ADD ONE:   the single new element to add in this frame

    If keep is not populated for an edit step, it is automatically inferred from
    the goals/deltas of all preceding steps so the model doesn't erase them.
    """
    steps = plan.get("steps", [])
    if not steps or step_idx > len(steps):
        return "No step specification found."

    step = steps[step_idx - 1]
    forbidden = step.get("forbidden") if isinstance(step.get("forbidden"), list) else []
    keep = step.get("keep") if isinstance(step.get("keep"), list) else []
    add = step.get("add") if isinstance(step.get("add"), list) else []
    if not add:
        add = [step.get("delta", step.get("goal", f"Step {step_idx}"))]

    if not keep and step_idx > 1:
        keep = [f"{s.get('goal', f'Step {i+1}')}: {s.get('delta', '')}" for i, s in enumerate(steps[: step_idx - 1])]

    lines = ["FORBIDDEN:"]
    if forbidden:
        lines.extend([f"- {x}" for x in forbidden])
    elif step_idx == 1:
        lines.append("- none (first frame)")
    else:
        lines.append("- do not redraw any existing element")

    lines.append("\nKEEP:")
    if keep:
        lines.extend([f"- {x}" for x in keep])
    else:
        lines.append("- none")

    lines.append("\nADD ONE:")
    lines.extend([f"- {x}" for x in add])
    return "\n".join(lines)


def _build_render_contract(plan: dict, step_idx: int) -> str:
    """Stricter execution contract to reduce model improvisation in edits."""
    steps = plan.get("steps", [])
    if not steps or step_idx > len(steps):
        return "RENDER CONTRACT:\n- no step data found"

    step = steps[step_idx - 1]
    forbidden = step.get("forbidden") if isinstance(step.get("forbidden"), list) else []
    keep = step.get("keep") if isinstance(step.get("keep"), list) else []
    add = step.get("add") if isinstance(step.get("add"), list) else []
    if not add:
        add = [str(step.get("delta", step.get("goal", f"Step {step_idx}")))]

    add_arrow_items = [str(x) for x in add if "arrow" in str(x).lower() or "->" in str(x) or "→" in str(x)]

    lines = [
        "RENDER CONTRACT (STRICT):",
        f"- step_index: {step_idx}",
        f"- keep_count: {len(keep)}",
        f"- add_count: {len(add)}",
        "- Preserve every existing object, label, and arrow unless explicitly listed in FORBIDDEN.",
        "- Add only the ADD ONE content. Do not add extra objects, extra labels, or extra arrows.",
        "- Do not move or resize existing key objects unless required by ADD ONE.",
        "- Keep all previously readable labels readable after the edit.",
    ]

    if forbidden:
        lines.append("- Forbidden details:")
        lines.extend([f"  - {x}" for x in forbidden])

    if add_arrow_items:
        lines.append("- Arrow constraints:")
        lines.append("  - For each ADD item that mentions an arrow, draw exactly one corresponding arrow relation.")
        lines.append("  - Do not reverse arrow direction. Keep source->target semantics exactly as written.")
        lines.append("  - Do not duplicate arrow-label pairs for the same relation.")

    lines.append("INTERNAL SELF-CHECK (do not output text in image):")
    lines.append("- Is every ADD item present?")
    lines.append("- Is any non-requested object present? If yes, remove it.")
    lines.append("- Is any old key object occluded by new content? If yes, reposition new content.")
    lines.append("- If arrows exist, are their directions semantically correct and non-redundant?")
    return "\n".join(lines)


_UNIVERSAL_RULES = """ABSOLUTE RULES:
- flat 2D educational style, no photorealism
- no shadows, no 3D perspective
- keep bottom y=800-1024 empty white
- preserve all existing elements exactly in edit steps
- add only what is listed in ADD ONE
- do not cover, hide, or visually block previously drawn key objects/labels/arrows
- place new elements in open space; if space is tight, make the new element smaller rather than occluding old content
- if a formula tile exists: draw tile background only; Python overlays formula text
- the image must visually explain the provided question and correct explanation, not just look plausible
- do not substitute unrelated objects or generic infographic decorations
- optimize for student comprehension, not visual flair
- use low clutter, high contrast, stable layout, and minimal label density
- each frame should communicate one teachable idea clearly for the target grade level
- avoid misleading simplifications or visuals that create misconceptions
- arrows must be semantically correct: one directional arrow per causal relation, with clear arrowhead direction
- avoid redundant arrows or duplicate arrow-label pairs that repeat the same relation
"""


def build_first_frame_prompt(plan: dict) -> str:
    return (
        "TASK: Generate frame 1 of 7 educational storyboard.\n\n"
        + _build_story_context(plan, 1)
        + "\n\n"
        + _build_canvas_zones(plan)
        + "\n\n"
        + _build_notation(plan)
        + "\n\n"
        + _plan_spec_block(plan, 1)
        + "\n\n"
        + _build_render_contract(plan, 1)
        + "\n\n"
        + _UNIVERSAL_RULES
    )


def build_edit_prompt(plan: dict, step_idx: int) -> str:
    return (
        "TASK: In-painting edit. Preserve existing diagram and add ONE new element.\n\n"
        + "EDIT POLICY: Never block previous key content; new additions must keep all existing explanatory content legible.\n\n"
        + _build_story_context(plan, step_idx)
        + "\n\n"
        + _build_canvas_zones(plan)
        + "\n\n"
        + _build_notation(plan)
        + "\n\n"
        + _plan_spec_block(plan, step_idx)
        + "\n\n"
        + _build_render_contract(plan, step_idx)
        + "\n\n"
        + _UNIVERSAL_RULES
    )
